верстает index первой части задания
htmlacademy-adaptive/1123257-mishka-22 pull request #2
Opened 2021-04-01 09:48 UTC by Vkhv73

2021-04-01 18:37 UTC, PavelNyukalo requested changes

2021-04-01 18:37 UTC, PavelNyukalo commented on source/index.html
> +        </nav>
Пока можешь оставить так, но будь готов, что при построении сеток возможно придется переделать списки, поскольку будет сложно оторвать один элемент с поиском от остального списка, вставить туда лого, что-то вниз переместить и тд
![image](https://user-images.githubusercontent.com/52506235/113335194-066d1680-933e-11eb-871b-1897af212771.png)

А еще в блоке `user-nav` у ссылки другой класс надо, не такой же как у самого блока

2021-04-01 18:37 UTC, PavelNyukalo commented on source/index.html
> +      </section>
1. Здесь так же предлагаю `page-header__bottom`
2. Заголовку и тексту о доставке не надо `visually-hidden`
3. `option-one/two` два отдельных блока получаются, давай может в `div class="featured-option"` завернем? И ссылки уже `featured-option__link featured-option__link--toys` и тд

2021-04-01 18:37 UTC, PavelNyukalo commented on source/index.html
> +        <h1>Вязаные корзинки</h1>
Тут и остальные ниже поправь на `h2`

2021-04-01 18:37 UTC, PavelNyukalo commented on source/index.html
> +      </section>
Тут в целом много блоков получается, которые по сути являются _элементами_ _блока_ `main-action`. Тот же `action-subtytle` (только subt**i**tle) в отдельный блок не завернуть, он смысла никакого по отдельности не дает. А вот `button` - да, переиспользуемый, тут норм. В итоге будет `main-action__subtitle/text/options`

2021-04-01 18:37 UTC, PavelNyukalo commented on source/index.html
> +      </section>
Тоже много отдельных блоков. В принципе блок не сложный тут, можно все к одному свести: 
```
main-about
main-about__list
main-about__item
```

2021-04-01 18:37 UTC, PavelNyukalo commented on source/index.html
> +          </li>
Вынести в отдельный блок отзывы - ок.
Только можно примиксовать например `main-reviews__list reviews-list`
И тогда дальше будет не `reviews-item`, а `reviews-list__item` и т.д. А `current` можно модификатором сделать `reviews-list__item--current`

2021-04-01 18:37 UTC, PavelNyukalo commented on source/index.html
> +        </ul>
Здесь тоже давай примиксуем `main-reviews__pagination pagination-list`. И дальше так же `pagination-list__item`, `pagination-list__link`

2021-04-01 18:37 UTC, PavelNyukalo commented on source/index.html
> +    </footer>
Насчет футера:
1. Думаю, блок с контактами надо вынести из футера - поскольку на других страницах его нет
2. В таком случае не надо будет `footer-top` и тд
3. Так же с названиями посмотри, переделай
4. Внутри уже самого футера можно секции не делать - а `div`ами заменить

2021-04-01 18:37 UTC, PavelNyukalo commented on source/index.html
> +        </section>
А еще насчет контактов:
тут можно таблицу не делать, а проще сделать
![image](https://user-images.githubusercontent.com/52506235/113338867-2226eb80-9343-11eb-8c0a-908d5445a185.png)

2021-04-05 09:03 UTC, Vkhv73 commented on source/index.html
> +      <section class="header-top">
1 corrected

2021-04-05 09:10 UTC, Vkhv73 commented on source/index.html
> +        </nav>
1 corrected

2021-04-05 09:11 UTC, Vkhv73 commented on source/index.html
> +      </section>
1 corrected

2021-04-05 09:13 UTC, Vkhv73 commented on source/index.html
> +        <h1>Вязаные корзинки</h1>
1 corrected

2021-04-05 09:28 UTC, Vkhv73 commented on source/index.html
> +      </section>
1 corrected

2021-04-05 09:29 UTC, Vkhv73 commented on source/index.html
> +      </section>
1 corrected

2021-04-05 09:54 UTC, Vkhv73 commented on source/index.html
> +          </li>
1 corrected Как понял.

2021-04-05 09:58 UTC, Vkhv73 commented on source/index.html
> +        </ul>
1 corrected Как понял.

2021-04-05 14:31 UTC, PavelNyukalo requested changes

2021-04-05 14:31 UTC, PavelNyukalo commented on source/index.html
> +          <a class="featured-option__link--toy" href="#">Детские игрушки <img src="img/mobile/toy-svg.svg" alt=""></a>
Здесь модификатор применяется к элементу, но самого элемента нет, т.е. должно быть `class="featured-option__link featured-option__link--interior"`

2021-04-05 14:31 UTC, PavelNyukalo commented on source/index.html
>            </li>
Здесь также применяются модификаторы к элементам без самих элементов. Т.е тот же текущий слайд будет не просто `class="reviews-list__item--current`, а `class="reviews-list__item reviews-list__item--current`.  
А вот `reviews-list__item--text` можно сделать отдельным элементом - `reviews-list__text` и т.д

2021-04-05 14:31 UTC, PavelNyukalo commented on source/index.html
>        </div>
Футер тоже переделаем на консультации по примеру [демки](https://up.htmlacademy.ru/adaptive/22/demos/5133#76)

2021-04-05 18:35 UTC, Vkhv73 commented on source/index.html
> +          <a class="featured-option__link--toy" href="#">Детские игрушки <img src="img/mobile/toy-svg.svg" alt=""></a>
Исправил. Убрал вообще модификатор. Стилизовать, думаю, получится только по элементу.

2021-04-05 19:17 UTC, Vkhv73 commented on source/index.html
>        </div>
Вроде бы исправил

2021-04-05 19:18 UTC, Vkhv73 commented on source/index.html
>            </li>
Исправил.

2021-04-06 08:48 UTC, PavelNyukalo approved these changes

2021-04-06 08:48 UTC, merged